;; pairs are (package-name package-version-list

((browse-kill-ring . nil)
 (coffee-mode . nil)
 (color-theme . nil)
 (deft . nil)
 (find-file-in-git-repo . nil)
 (find-file-in-project . nil)
 (full-ack . nil)
 (haskell-mode . nil)
 (lambdacalc . nil)
 (magit . nil)
 (markdown-mode . nil)
 (paredit . nil)
 (scala-mode . nil)
 (smex . nil)
 (sr-speedbar . nil)
 (starter-kit . nil)
 (starter-kit-bindings . nil)
 (starter-kit-eshell . nil)
 (starter-kit-js . nil)
 (starter-kit-lisp . nil)
 (starter-kit-ruby . nil)
 (yaml-mode . nil)
 (auto-complete . nil))
